"""Tier 2 import-map rules (sigil-effect-inference skill, step 1).

Dotted-path rules, longest prefix wins. Split from effects.py to honor the
400-line file limit (CLAUDE.md). Rule changes follow the benchmark protocol:
every newly discovered miss becomes a numbered fixture BEFORE it is fixed
(see case_031, decisions.md D-009).
"""

from __future__ import annotations

# (emit_on_call, result_taint). result_taint may be "dynamic".
# Longest dotted prefix wins; (None, None) = known pure.
PATH_RULES: dict[str, tuple[str | None, str | None]] = {
    "requests": ("net", "net"),
    "httpx": ("net", "net"),
    "urllib": ("net", "net"),
    "socket": ("net", "net"),
    "aiohttp": ("net", "net"),
    "http.cookiejar": (None, None),
    "http.cookies": (None, None),
    "http.HTTPStatus": (None, None),
    "http": ("net", "net"),
    "urllib.parse": (None, None),
    "urllib.error": (None, None),
    "ftplib": ("net", "net"),
    "smtplib": ("net", "net"),
    "pathlib": (None, "fs"),  # constructing a Path is pure; the value is fs-capable
    "shutil": ("fs", None),
    "tempfile": ("fs.write", "fs"),
    "io.open": ("fs", "fs"),
    "glob": ("fs.read", None),
    "fileinput": ("fs", "fs"),
    "zipfile": ("fs", "fs"),
    "tarfile": ("fs", "fs"),
    "sqlite3": ("db", "db"),
    "pickle.load": ("unsafe", None),
    "pickle.loads": ("unsafe", None),
    "pickle": (None, None),
    "random": ("rand", None),
    "secrets": ("rand", None),
    "uuid.uuid4": ("rand", None),
    "uuid": (None, None),
    "os.urandom": ("rand", None),
    "time": ("clock", None),
    "datetime": ("clock", None),
    # os.path: string manipulation is pure, but the predicates/readers DO
    # touch the filesystem (found by the requests spot-check; fixture case_031).
    "os.path.exists": ("fs.read", None),
    "os.path.isfile": ("fs.read", None),
    "os.path.isdir": ("fs.read", None),
    "os.path.islink": ("fs.read", None),
    "os.path.ismount": ("fs.read", None),
    "os.path.lexists": ("fs.read", None),
    "os.path.getsize": ("fs.read", None),
    "os.path.getmtime": ("fs.read", None),
    "os.path.getatime": ("fs.read", None),
    "os.path.getctime": ("fs.read", None),
    "os.path.samefile": ("fs.read", None),
    "os.path.realpath": ("fs.read", None),
    "os.path.expanduser": ("env", None),
    "os.path.expandvars": ("env", None),
    "os.path": (None, None),
    "os.environ": ("env", "env"),
    "os.getenv": ("env", None),
    "os.putenv": ("env", None),
    "os.remove": ("fs.write", None),
    "os.unlink": ("fs.write", None),
    "os.mkdir": ("fs.write", None),
    "os.makedirs": ("fs.write", None),
    "os.rmdir": ("fs.write", None),
    "os.rename": ("fs.write", None),
    "os.replace": ("fs.write", None),
    "os.listdir": ("fs.read", None),
    "os.scandir": ("fs.read", "fs"),
    "os.stat": ("fs.read", None),
    "os.walk": ("fs.read", None),
    "os.open": ("fs", "fs"),
    "os.read": ("fs.read", None),
    "os.write": ("fs.write", None),
    "os.chmod": ("fs.write", None),
    "os.chown": ("fs.write", None),
    "os.getcwd": ("env", None),
    "os.system": ("unsafe", None),
    "os.popen": ("unsafe", None),
    "os.exec": ("unsafe", None),
    "os.spawn": ("unsafe", None),
    "os.fork": ("unsafe", None),
    "os.kill": ("unsafe", None),
    "os": ("env", None),  # PoC default for the rest of os.*; over-report is acceptable
    "subprocess": ("unsafe", None),
    "ctypes": ("unsafe", None),
    "importlib": ("unsafe", None),
    "multiprocessing": ("unsafe", None),
    "threading": ("unsafe", None),
    "signal": ("unsafe", None),
    "logging": ("io", None),
    "print": ("io", None),
    "warnings": ("io", None),
    "sys.stdout": ("io", "io"),
    "sys.stderr": ("io", "io"),
    "sys.stdin": ("io", "io"),
    "sys.exit": (None, None),
    "sys": (None, None),
    "functools.partial": (None, "dynamic"),
    "functools": (None, None),
    # Known-pure stdlib roots (silence is safe here, not an under-report).
    "json": (None, None),
    "math": (None, None),
    "re": (None, None),
    "itertools": (None, None),
    "collections": (None, None),
    "string": (None, None),
    "textwrap": (None, None),
    "typing": (None, None),
    "dataclasses": (None, None),
    "enum": (None, None),
    "abc": (None, None),
    "copy": (None, None),
    "heapq": (None, None),
    "bisect": (None, None),
    "operator": (None, None),
    "statistics": (None, None),
    "decimal": (None, None),
    "fractions": (None, None),
    "hashlib": (None, None),
    "base64": (None, None),
    "struct": (None, None),
    "unicodedata": (None, None),
    "difflib": (None, None),
    "fnmatch": (None, None),
    "pprint": ("io", None),
    "traceback": (None, None),
    "inspect": (None, None),
    # Builtins (aliasing-safe: f = open still resolves through here).
    "builtins.open": ("fs", "fs"),
    "builtins.print": ("io", None),
    "builtins.input": ("io", None),
    "builtins.eval": ("unsafe", None),
    "builtins.exec": ("unsafe", None),
    "builtins.compile": ("unsafe", None),
    "builtins.__import__": ("unsafe", None),
    "builtins.getattr": (None, "dynamic"),
    "builtins.setattr": ("mut", None),
    "builtins.delattr": ("mut", None),
    "builtins.globals": (None, "dynamic"),
    "builtins.locals": (None, None),
    "builtins.vars": (None, None),
    "builtins": (None, None),  # everything else (len, str, sorted, ...) is pure
}

# Annotation names that taint a parameter with a capability.
ANNOTATION_TAINTS: dict[str, str] = {
    "pathlib.Path": "fs",
    "pathlib.PurePath": "fs",
    "pathlib.PosixPath": "fs",
    "pathlib.WindowsPath": "fs",
    "typing.IO": "fs",
    "typing.TextIO": "fs",
    "typing.BinaryIO": "fs",
    "socket.socket": "net",
}
