#!/usr/bin/env python3
"""Scripted agent session (plan section 9, example 3): an AI fixes a seeded
bug via patches only, with cost accounting per R1-R3. Run me directly."""

import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))
sys.dont_write_bytecode = True

from sigil.harness.context import est_tokens  # noqa: E402
from sigil.harness.core import Harness  # noqa: E402

SEEDED = (Path(__file__).parent / "mathx.sg").read_text()
log: list[str] = []


def say(role: str, text: str) -> None:
    log.append(f"**{role}:** {text}")


with tempfile.TemporaryDirectory() as tmp:
    h = Harness(tmp)
    info = h.load_sigil_source(SEEDED, name="mathx")
    full_file_cost = est_tokens(SEEDED)

    say("harness", f"module loaded; sheet:\n```\n{h.sheet()}\n```")
    sheet_cost = est_tokens(h.sheet())

    v = h.verify(info["goals"]["triple"], inputs={"n": 4})
    failing = next(c for c in v["clauses"] if not c[1])
    say("harness", f"verify: **{v['status']}** — `{failing[0]}` with {failing[2]}")

    src = h.expand(info["fns"]["triple"])
    expand_cost = est_tokens(src)
    say(
        "agent",
        f"expand impl only ({expand_cost} tok, not the {full_file_cost}-tok file):"
        f"\n```\n{src}\n```",
    )

    ops = [{"path": "body.stmts.0.value.right.val", "op": "replace", "value": "3"}]
    result = h.patch(info["fns"]["triple"], ops, inputs={"n": 4})
    patch_cost = est_tokens(str(ops))
    say("agent", f"patch ({patch_cost} tok of output): `{ops[0]['path']} := 3`")
    say(
        "harness",
        f"auto-verify (R3): **{result['verify']['status']}** — goal now "
        f"{h.store.status(info['goals']['triple'])}",
    )

    say("harness", f"sheet after (R1 — earlier lines unchanged):\n```\n{h.sheet()}\n```")
    stats = h.session_close()
    say("harness", f"session stats: {stats['stats']}")

    costs = (
        f"| context route | est tokens |\n|---|---|\n"
        f"| full source file | {full_file_cost} |\n"
        f"| digest sheet (R1) | {sheet_cost} |\n"
        f"| expand impl only (R2) | {expand_cost} |\n"
        f"| patch output (R3 input to next turn) | {patch_cost} |"
    )

transcript = (
    "# Agent session transcript — seeded bug fixed via patches only\n\n"
    "Generated by run_session.py. The agent never reads or writes a file: "
    "sheet -> verify -> expand -> patch -> auto-verify.\n\n"
    + "\n\n".join(log)
    + "\n\n## Cost accounting (chars/4 estimate)\n\n"
    + costs
    + "\n"
)
out = Path(__file__).parent / "transcript.md"
out.write_text(transcript)
print(transcript)
print(f"\nwrote {out}")
