"""Generated by sigil build from module 'pricing' — edit the .sg, not this."""

import os as _os

__sigil_contracts__ = _os.environ.get("SIGIL_RELEASE") != "1"


def __sigil_set_insert(s, x):
    """Sigil Set.insert: add if absent, return whether it was added."""
    if x in s:
        return False
    s.add(x)
    return True


def apply_discount(price: int, pct: int) -> int:
    return ((price * (100 - pct)) / 100)

